### ISSUE TITLE
The issue occurs when split.writeToCsv() is called

### ISSUE THREAD

**Issue by chen-hanliang** [tony10101105/Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection#1]
Traceback (most recent call last):
  File "C:\Users\Desktop\Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection-main\Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection-main\main_pyod.py", line 3, in <module>
    split.writeToCsv()
  File "C:\Users\Desktop\Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection-main\Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection-main\split.py", line 31, in writeToCsv
    writer.writerow([trainData[i][0]+[trainData[i][1]]])
TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'

**Comment by MarkeyGeng** [comment]
![image](https://github.com/tony10101105/Locally-Interpretable-One-Class-Anomaly-Detection-for-Credit-Card-Fraud-Detection/assets/50792384/4aea7afa-dbc0-4f49-9bc7-a69c52626504)
In main.py Line129, you make 'g_loss = Re_Loss' + BCE_Loss, but in line130, you make 'g_loss = Re_Loss' again. Could you please tell me the reason for doing this?

**Comment by tony10101105** [comment]
Hi,
That may be a version issue. We kept doing stuff with the code after paper submission and some lines might be inadvertently altered. You can just comment out line130.

**Comment by MarkeyGeng** [comment]
fine，thanks for your answer！I would like to ask again, is this version of the code the final code and are the code running results consistent with the experimental results in the paper ?

**Comment by tony10101105** [comment]
Hi,
Sorry I missed the notifications. Hope you are doing well. Yes, but note that this dataset has no official split, so we set up a random seed to split the train/test set. And since one-class anomaly detection is highly sensitive to data distribution, a different train/test split may require you so re-tune the training parameters to achieve a good result.
